name: Pull Request Check

on:
  pull_request:
    branches:
      - master

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 10
          - 12
          - 14
          - 16

    name: NodeJS v${{ matrix.node_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      
      - run: npm ci
      - run: npm run lint
      - run: npm run check-types
      - run: npm run build
      - run: npm run test
